import { Participant, Customer, Account, LedgerAccount } from '@/types';

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'bank-a',
    code: 'NAIJANG',
    name: 'Naija Bank',
    routingCode: '011',
    status: 'ONLINE',
    supportedMessages: ['acmt.023.001.03', 'acmt.024.001.03', 'pacs.008.001.10', 'pacs.002.001.12', 'camt.052.001.08', 'camt.053.001.08', 'pain.013.001.07'],
    capabilities: {
      instantTransfer: true,
      directDebit: true,
      requestToPay: true,
      camtReporting: true,
    },
    brandColor: '#059669', // Emerald
    accentColor: '#10B981',
    endpoint: '/api/banks/NAIJANG/inbound',
  },
  {
    id: 'bank-b',
    code: 'UNITNG',
    name: 'Unity Bank',
    routingCode: '022',
    status: 'ONLINE',
    supportedMessages: ['acmt.023.001.03', 'acmt.024.001.03', 'pacs.008.001.10', 'pacs.002.001.12', 'camt.052.001.08', 'camt.053.001.08'],
    capabilities: {
      instantTransfer: true,
      directDebit: true,
      requestToPay: false,
      camtReporting: true,
    },
    brandColor: '#1D4ED8', // Royal Blue
    accentColor: '#3B82F6',
    endpoint: '/api/banks/UNITNG/inbound',
  },
  {
    id: 'bank-c',
    code: 'METRNG',
    name: 'Metro Bank',
    routingCode: '033',
    status: 'ONLINE',
    supportedMessages: ['acmt.023.001.03', 'acmt.024.001.03', 'pacs.008.001.10', 'pacs.002.001.12', 'camt.052.001.08', 'camt.053.001.08', 'pain.013.001.07'],
    capabilities: {
      instantTransfer: true,
      directDebit: true,
      requestToPay: true,
      camtReporting: true,
    },
    brandColor: '#E11D48', // Crimson / Rose
    accentColor: '#F43F5E',
    endpoint: '/api/banks/METRNG/inbound',
  },
  {
    id: 'bank-d',
    code: 'NOVANG',
    name: 'Nova Bank',
    routingCode: '044',
    status: 'ONLINE',
    supportedMessages: ['acmt.023.001.03', 'acmt.024.001.03', 'pacs.008.001.10', 'pacs.002.001.12', 'camt.052.001.08'],
    capabilities: {
      instantTransfer: true,
      directDebit: true,
      requestToPay: true,
      camtReporting: false,
    },
    brandColor: '#7C3AED', // Purple
    accentColor: '#8B5CF6',
    endpoint: '/api/banks/NOVANG/inbound',
  },
  {
    id: 'bank-e',
    code: 'PARANG',
    name: 'Parallel Bank',
    routingCode: '055',
    status: 'ONLINE',
    supportedMessages: ['acmt.023.001.03', 'acmt.024.001.03', 'pacs.008.001.10', 'pacs.002.001.12', 'camt.052.001.08', 'camt.053.001.08'],
    capabilities: {
      instantTransfer: true,
      directDebit: false,
      requestToPay: true,
      camtReporting: true,
    },
    brandColor: '#D97706', // Amber
    accentColor: '#F59E0B',
    endpoint: '/api/banks/PARANG/inbound',
  },
  {
    id: 'pseudo-inst',
    code: 'PSEUNG',
    name: 'Apex Direct Debit Gateway (Pseudo Inst)',
    routingCode: '998',
    status: 'ONLINE',
    supportedMessages: ['pain.008.001.11', 'pacs.003.001.11', 'pacs.002.001.12', 'pain.002.001.14'],
    capabilities: {
      instantTransfer: true,
      directDebit: true,
      requestToPay: true,
      camtReporting: true,
    },
    brandColor: '#0284C7', // Sky Blue
    accentColor: '#38BDF8',
    endpoint: '/api/banks/PSEUNG/inbound',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-a1',
    institutionId: 'bank-a',
    fullName: 'Fred Okon',
    email: 'fred.okon@naijabank.sim',
    phone: '+234 802 100 0001',
    status: 'ACTIVE',
  },
  {
    id: 'cust-a2',
    institutionId: 'bank-a',
    fullName: 'Zainab Ahmed',
    email: 'zainab.ahmed@naijabank.sim',
    phone: '+234 802 100 0002',
    status: 'ACTIVE',
  },
  {
    id: 'cust-b1',
    institutionId: 'bank-b',
    fullName: 'Chukwuma Obi',
    email: 'c.obi@unitybank.sim',
    phone: '+234 803 200 0001',
    status: 'ACTIVE',
  },
  {
    id: 'cust-b2',
    institutionId: 'bank-b',
    fullName: 'Fatima Bello',
    email: 'f.bello@unitybank.sim',
    phone: '+234 803 200 0002',
    status: 'ACTIVE',
  },
  {
    id: 'cust-c1',
    institutionId: 'bank-c',
    fullName: 'Adaeze Okafor',
    email: 'adaeze.o@metrobank.sim',
    phone: '+234 805 300 0001',
    status: 'ACTIVE',
  },
  {
    id: 'cust-c2',
    institutionId: 'bank-c',
    fullName: 'Babatunde Adeleke',
    email: 'tunde.ade@metrobank.sim',
    phone: '+234 805 300 0002',
    status: 'ACTIVE',
  },
  {
    id: 'cust-d1',
    institutionId: 'bank-d',
    fullName: 'David Adeleke',
    email: 'david.a@novabank.sim',
    phone: '+234 807 400 0001',
    status: 'ACTIVE',
  },
  {
    id: 'cust-d2',
    institutionId: 'bank-d',
    fullName: 'Ngozi Eze',
    email: 'ngozi.eze@novabank.sim',
    phone: '+234 807 400 0002',
    status: 'ACTIVE',
  },
  {
    id: 'cust-e1',
    institutionId: 'bank-e',
    fullName: 'Tunde Bakare',
    email: 'tunde.b@parallelbank.sim',
    phone: '+234 809 500 0001',
    status: 'ACTIVE',
  },
  {
    id: 'cust-e2',
    institutionId: 'bank-e',
    fullName: 'Aisha Yusuf',
    email: 'aisha.y@parallelbank.sim',
    phone: '+234 809 500 0002',
    status: 'ACTIVE',
  },
  {
    id: 'cust-pseudo',
    institutionId: 'pseudo-inst',
    fullName: 'PowerGrid Utilities (Biller)',
    email: 'collections@powergrid.sim',
    phone: '+234 800 000 9999',
    status: 'ACTIVE',
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acct-a1',
    institutionId: 'bank-a',
    customerId: 'cust-a1',
    accountNumber: '0112345678',
    accountName: 'Fred Okon - Savings',
    accountType: 'SAVINGS',
    availableBalance: 2450000.00,
    ledgerBalance: 2450000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-a2',
    institutionId: 'bank-a',
    customerId: 'cust-a2',
    accountNumber: '0119876543',
    accountName: 'Zainab Ahmed - Current',
    accountType: 'CURRENT',
    availableBalance: 500000.00,
    ledgerBalance: 500000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-b1',
    institutionId: 'bank-b',
    customerId: 'cust-b1',
    accountNumber: '0221122334',
    accountName: 'Chukwuma Obi - Current',
    accountType: 'CURRENT',
    availableBalance: 1200000.00,
    ledgerBalance: 1200000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-b2',
    institutionId: 'bank-b',
    customerId: 'cust-b2',
    accountNumber: '0225566778',
    accountName: 'Fatima Bello - Corporate',
    accountType: 'CORPORATE',
    availableBalance: 3150000.00,
    ledgerBalance: 3150000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-c1',
    institutionId: 'bank-c',
    customerId: 'cust-c1',
    accountNumber: '0334455667',
    accountName: 'Adaeze Okafor - Savings',
    accountType: 'SAVINGS',
    availableBalance: 850000.00,
    ledgerBalance: 850000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-c2',
    institutionId: 'bank-c',
    customerId: 'cust-c2',
    accountNumber: '0338899001',
    accountName: 'Babatunde Adeleke - Current',
    accountType: 'CURRENT',
    availableBalance: 640000.00,
    ledgerBalance: 640000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-d1',
    institutionId: 'bank-d',
    customerId: 'cust-d1',
    accountNumber: '0441234567',
    accountName: 'David Adeleke - Premium',
    accountType: 'CURRENT',
    availableBalance: 3700000.00,
    ledgerBalance: 3700000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-d2',
    institutionId: 'bank-d',
    customerId: 'cust-d2',
    accountNumber: '0447654321',
    accountName: 'Ngozi Eze - Savings',
    accountType: 'SAVINGS',
    availableBalance: 180000.00,
    ledgerBalance: 180000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-e1',
    institutionId: 'bank-e',
    customerId: 'cust-e1',
    accountNumber: '0553344556',
    accountName: 'Tunde Bakare - Corporate',
    accountType: 'CORPORATE',
    availableBalance: 5000000.00,
    ledgerBalance: 5000000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-e2',
    institutionId: 'bank-e',
    customerId: 'cust-e2',
    accountNumber: '0559988776',
    accountName: 'Aisha Yusuf - Savings',
    accountType: 'SAVINGS',
    availableBalance: 920000.00,
    ledgerBalance: 920000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
  {
    id: 'acct-pseudo1',
    institutionId: 'pseudo-inst',
    customerId: 'cust-pseudo',
    accountNumber: '9981122334',
    accountName: 'PowerGrid Collections - Corporate',
    accountType: 'CORPORATE',
    availableBalance: 10000000.00,
    ledgerBalance: 10000000.00,
    currency: 'NGN',
    status: 'ACTIVE',
  },
];

export const INITIAL_LEDGER_ACCOUNTS: LedgerAccount[] = [
  // Bank A
  { id: 'ldg-a-dep', institutionId: 'bank-a', code: '1010-CUST-DEP', name: 'Customer Deposits (Liabilities)', type: 'LIABILITY', balance: 2950000, currency: 'NGN' },
  { id: 'ldg-a-clr', institutionId: 'bank-a', code: '1020-SETTLE-CLR', name: 'Central Bank Settlement Clearing', type: 'ASSET', balance: 50000000, currency: 'NGN' },
  // Bank B
  { id: 'ldg-b-dep', institutionId: 'bank-b', code: '1010-CUST-DEP', name: 'Customer Deposits (Liabilities)', type: 'LIABILITY', balance: 4350000, currency: 'NGN' },
  { id: 'ldg-b-clr', institutionId: 'bank-b', code: '1020-SETTLE-CLR', name: 'Central Bank Settlement Clearing', type: 'ASSET', balance: 50000000, currency: 'NGN' },
  // Bank C
  { id: 'ldg-c-dep', institutionId: 'bank-c', code: '1010-CUST-DEP', name: 'Customer Deposits (Liabilities)', type: 'LIABILITY', balance: 1490000, currency: 'NGN' },
  { id: 'ldg-c-clr', institutionId: 'bank-c', code: '1020-SETTLE-CLR', name: 'Central Bank Settlement Clearing', type: 'ASSET', balance: 50000000, currency: 'NGN' },
  // Bank D
  { id: 'ldg-d-dep', institutionId: 'bank-d', code: '1010-CUST-DEP', name: 'Customer Deposits (Liabilities)', type: 'LIABILITY', balance: 3880000, currency: 'NGN' },
  { id: 'ldg-d-clr', institutionId: 'bank-d', code: '1020-SETTLE-CLR', name: 'Central Bank Settlement Clearing', type: 'ASSET', balance: 50000000, currency: 'NGN' },
  // Bank E
  { id: 'ldg-e-dep', institutionId: 'bank-e', code: '1010-CUST-DEP', name: 'Customer Deposits (Liabilities)', type: 'LIABILITY', balance: 5920000, currency: 'NGN' },
  { id: 'ldg-e-clr', institutionId: 'bank-e', code: '1020-SETTLE-CLR', name: 'Central Bank Settlement Clearing', type: 'ASSET', balance: 50000000, currency: 'NGN' },
  // Pseudo Institution (Direct Debit Gateway)
  { id: 'ldg-pseudo-inst-dep', institutionId: 'pseudo-inst', code: '1010-CUST-DEP', name: 'Customer Deposits (Liabilities)', type: 'LIABILITY', balance: 10000000, currency: 'NGN' },
  { id: 'ldg-pseudo-inst-clr', institutionId: 'pseudo-inst', code: '1020-SETTLE-CLR', name: 'Central Bank Settlement Clearing', type: 'ASSET', balance: 50000000, currency: 'NGN' },
];
